### ISSUE TITLE
Naked can't find node when running with Gunicorn server

### ISSUE THREAD

**Issue by allthetime** [chrissimpkins/naked#21]
Hi, I'm trying to run some node code from a python API behind a gunicorn server.

When `execute_js` is called, I just get this:

`/bin/sh: 1: node: not found`

Is there a way to set the path to node?

**Comment by chrissimpkins** [comment]
Unfortunately not in that function.  Here is the source:

https://github.com/chrissimpkins/naked/blob/692ade138446422abda94c68d142293bcd4f8b65/lib/Naked/toolshed/shell.py#L155-L165

It is hard coded to call `node [script] [args]`. 

But you can switch to the `execute` function in the same module (instead of `execute_js` and write the absolute path to node on the server followed by the arguments and pass the entire string to the function as the full command:

https://github.com/chrissimpkins/naked/blob/692ade138446422abda94c68d142293bcd4f8b65/lib/Naked/toolshed/shell.py#L15-L30

**Comment by allthetime** [comment]
@chrissimpkins Thanks for the detail! I ended up solving it by explicitly setting the path to node in my supervisor configuration.

**Comment by chrissimpkins** [comment]
Great!  Let me know if you need anything else.
